# HomeWork01

### **1** Создание одномерного массива arr1 из списка [5, 10, 15, 20, 25].

In [4]:
import numpy as np
arr1 = np.array([5, 10, 15, 20, 25])
print(arr1)

[ 5 10 15 20 25]


### **2** Двумерный массив arr размером 3x4, заполненный нулями.

In [5]:
import numpy as np
arr2 = np.zeros((3, 4))
print(arr2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **3** Одномерный массив с числами от 0 до 9.

In [98]:
import numpy as np
arr3 = np.arange(0,10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


### **4** 	Массив	10x10	со	случайными	значениями,	найти	минимум,	максимум	и	среднее	значение.

In [16]:
import numpy as np
arr4 = np.random.random((10,10))
min, max, mean = arr4.min(), arr4.max(), arr4.mean()
print(min,	max, mean)

0.0006288326258216959 0.9995853022304073 0.536892297831564


### **5** Форма и тип данных для массива arr2.

In [101]:
print("Форма массива:", arr2.shape)
print("Тип данных:", arr2.dtype)

Форма массива: (3, 4)
Тип данных: float64


### **6** Получить третий элемент массива arr1, массива arr3 извлеки подмассив с элементами от 3 до 7 и из массива arr4 получи элемент во второй строке, третьем столбце.

In [106]:
print(arr1[2]) #[ 5 10 15 20 25]

sub = arr3[3:7] #[[ 0  1  2  3  4]
 			    #[ 5  6  7  8  9]
 				#[10 11 12 13 14]
 				#[15 16 17 18 19]
 				#[20 21 22 23 24]]
print(sub)

elem = arr4[1, 2]
#print(arr4)
print(elem)

15
[3 4 5 6]
0.49559486054385604


### **7** Умножить каждый элемент arr1 на 2 и поэлементно сложить arr3 с самим собой.

In [103]:
print(arr1 * 2) #[ 5 10 15 20 25]

print("Сумма:", arr3.sum()) #[[ 0  1  2  3  4]
 			      #[ 5  6  7  8  9]
 				  #[10 11 12 13 14]
 				  #[15 16 17 18 19]
 				  #[20 21 22 23 24]]

[10 20 30 40 50]
Сумма: 45


### **8** 	Матрица 6х6 поменять две строки местами.

In [97]:
import numpy as np
arr5 = np.arange(36).reshape(6,6)
arr5[[0,1]]	= arr5[[1,0]]
print(arr5)

[[ 6  7  8  9 10 11]
 [ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


### **9** Матрица с	0 внутри, и	1 на границах. срезы.

In [90]:
import numpy as np
n = 5
table = np.zeros((n,n))
table[:1] = 1 # первоя строка
table[:,0] = 1 # левый крайний столбец
table[:,n-1] = 1 # правый крайний столбец
table[n-1] = 1 # нижняя строка
print(table)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### **10** Сортировка массива из случайных значений по	убыванию.

In [ ]:
import numpy as np
arr6 = np.random.randint(0, 100, 10)
print(np.sort(arr6)[::-1])


[87 80 75 64 47 26 19  9  8  4]
